channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - xarray
  - geocube
  - geopandas
  - pyyaml
  - gstools
  - numba
  - jupyterlab
  - bokeh
  - jupyter_bokeh
  - qgrid
  - sphinx
  - statsmodels
  - pip
  - pip:
    - sphinx-rtd-theme
